#!/usr/bin/env python3
"""
Phase 4 Master Validation for Reference Bridge 001 (RB-S10-001).

Runs all layer validators against the merged Phase 4 Golden and emits a
consolidated Phase 4 validation summary used by the PR-4 closeout.

Usage: python validate_phase4_master.py [--phase4-dir PATH]
"""

import argparse
import csv
import json
import os
import subprocess
import sys

PHASE4_BASE = "docs/apollo/step10/reference_bridge_001/phase4"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--phase4-dir", default=os.path.join(os.getcwd(), PHASE4_BASE))
    args = parser.parse_args()
    d = args.phase4_dir
    tools = os.path.join(d, "tools")

    validators = [
        ("Model Golden (geometry + structural)", "validate_phase4_golden.py"),
        ("Design Golden", "validate_phase4_design_golden.py"),
        ("Report + Drawing Golden", "validate_phase4_report_drawing_golden.py"),
    ]

    total_checks = 0
    passed_checks = 0
    rows = []
    for label, script in validators:
        p = os.path.join(tools, script)
        r = subprocess.run([sys.executable, p], capture_output=True, text=True)
        out = (r.stdout + r.stderr).strip()
        # parse first line "OVERALL: PASS (16/16 checks)"
        ok = "PASS" in out.splitlines()[0] if out else False
        import re
        m = re.search(r"\((\d+)/(\d+) checks\)", out)
        p_, t_ = (int(m.group(1)), int(m.group(2))) if m else (0, 0)
        total_checks += t_
        passed_checks += p_
        rows.append((label, script, "PASS" if ok else "FAIL", t_, p_))
        print(out.splitlines()[0])

    # overall
    overall = "PASS" if passed_checks == total_checks else "FAIL"
    print(f"\nMASTER OVERALL: {overall} ({passed_checks}/{total_checks} checks across 3 validators)")

    with open(os.path.join(d, "validation", "phase4_master_validation_summary.md"), "w") as f:
        f.write("# Phase 4 Master Validation Summary\n\n")
        f.write(f"## Overall\n\n**MASTER OVERALL: {overall}** ({passed_checks}/{total_checks} checks)\n\n")
        f.write("## Validators\n\n| Layer | Status | Checks |\n|-------|--------|--------|\n")
        for label, ok, _, t, p in rows:
            f.write(f"| {label} | {ok} | {p}/{t} |\n")
        f.write("\n## Golden totals\n\n")
        for g in ("reference_bridge_001_model_golden.csv",
                  "reference_bridge_001_design_golden.csv",
                  "reference_bridge_001_report_drawing_golden.csv"):
            pth = os.path.join(d, "golden", g)
            if os.path.exists(pth):
                n = sum(1 for _ in csv.DictReader(open(pth, newline="", encoding="utf-8")))
                f.write(f"- {g}: {n} records\n")
        f.write("\nGenerated by `tools/validate_phase4_master.py`.\n")

    print("master summary written to validation/phase4_master_validation_summary.md")
    return 0 if overall == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())