/**
 * Phase 3-8: ②上部工サンプル → ①道路線形 復元・補完（CASE B reverse）。
 *
 * Reconstructs a partial road alignment from superstructure sample facts with
 * strict status/provenance. Sample-declared numbers become CONFIRMED;
 * deterministically derived values DERIVED; estimates INFERRED; absent data
 * MISSING/DEFERRED. INFERRED values are NEVER auto-promoted to CONFIRMED.
 *
 * Fail-closed:
 *  - missing required facts (bridge length / spans / supports) throw
 *  - a self-reconstruction loop (①→②→①, same bridgeId) is rejected
 *  - no invented vertical/crossfall/horizontal-curve geometry
 */

import type { GeometrySnapshot } from "../apollo/geometry/types";
import type { BuildIntermediateInput } from "../liner/core/pipeline/pipeline";
import type { PierDraft, SpanDraft } from "../liner/schema/types";
import type { BridgeProjectReconstruction } from "../contracts/bridgeProject";
import { buildBridgeProjectAlignment } from "./alignmentAdapter";
import type { BridgeProjectAlignment, BridgeProjectSuperstructure } from "./types";
import { BridgeProjectAdapterError, BP_CODES, assertFinite, assertAscendingStations } from "./validation";
import { deriveStableUuid } from "../contracts/legacy/idStability";

export const RECONSTRUCTION_TOOL_ID = "spacer-bridge-project-reconstruction";

/** Shared facts extractable from a ② superstructure sample (CASE B source). */
export interface ReconstructionSampleFacts {
  readonly bridgeId: string;
  /** CONFIRMED: declared by the sample. */
  readonly bridgeLengthM: number;
  /** CONFIRMED: declared span lengths (m). */
  readonly spanLengthsM: number[];
  /** CONFIRMED: support ids in order. */
  readonly supportIds: string[];
  /** CONFIRMED when declared; otherwise DERIVED from span sums. */
  readonly supportStationsM?: number[];
  /** CONFIRMED when finite; otherwise DEFERRED. */
  readonly supportSkewRads?: (number | undefined)[];
  readonly deckWidthM?: number;
  /** SUPERSTRUCTURE-owned girder offsets (m). */
  readonly girderOffsetsM?: Record<string, number>;
  /** Sample document reference (id:revision) for provenance. */
  readonly sourceReference: string;
}

export interface ReconstructionOptions {
  readonly alignmentId?: string;
  /** Cycle guard: reject when the sample was generated by THIS bridge (①→②→①). */
  readonly generatingBridgeId?: string;
}

export interface ReconstructionResult {
  readonly draft: BuildIntermediateInput;
  readonly alignment: BridgeProjectAlignment;
  readonly reconstruction: BridgeProjectReconstruction;
}

function roundStation(station: number): number {
  return Math.round(station / 1e-6) * 1e-6;
}

/** Extract reconstruction facts from a ② GeometrySnapshot (natural ② output). */
export function reconstructionFactsFromSnapshot(snapshot: GeometrySnapshot): ReconstructionSampleFacts {
  const ref = snapshot.alignmentReferences[0];
  const supportStationsM = snapshot.supportLines.map((line) => line.stationM.value);
  const supportSkewRads = snapshot.supportLines.map((line) => line.skewRad.value);
  const girderOffsetsM: Record<string, number> = {};
  for (const line of snapshot.girderLines) {
    if (typeof line.offsetM.value === "number" && Number.isFinite(line.offsetM.value)) {
      girderOffsetsM[line.girderId] = line.offsetM.value;
    }
  }
  return {
    bridgeId: snapshot.bridgeId,
    bridgeLengthM: ref?.bridgeLengthM.value ?? 0,
    spanLengthsM: Array.isArray(ref?.spanLengthsM.value) ? (ref.spanLengthsM.value as number[]) : [],
    supportIds: snapshot.supportLines.map((line) => line.supportId),
    supportStationsM: supportStationsM.every((s) => typeof s === "number") ? (supportStationsM as number[]) : undefined,
    supportSkewRads: supportSkewRads.map((s) => (typeof s === "number" && Number.isFinite(s) ? s : undefined)),
    deckWidthM: snapshot.deckReferences[0]?.widthM.value,
    girderOffsetsM: Object.keys(girderOffsetsM).length > 0 ? girderOffsetsM : undefined,
    sourceReference: `snapshot:${snapshot.bridgeId}:${snapshot.fingerprint}`,
  };
}

/** Extract reconstruction facts from a BridgeProject.Superstructure record (+ spans/stations extras). */
export function reconstructionFactsFromSuperstructure(
  superstructure: BridgeProjectSuperstructure,
  extras: { spanLengthsM?: number[]; supportStationsM?: number[]; supportSkewRads?: (number | undefined)[] } = {},
): ReconstructionSampleFacts {
  const girderOffsetsM: Record<string, number> = {};
  for (const girder of superstructure.mainGirderArrangement) {
    if (girder.offsetM.value !== undefined) {
      girderOffsetsM[girder.girderId] = girder.offsetM.value;
    }
  }
  return {
    bridgeId: superstructure.bridgeId,
    bridgeLengthM: extras.spanLengthsM ? extras.spanLengthsM.reduce((a, s) => a + s, 0) : 0,
    spanLengthsM: extras.spanLengthsM ?? [],
    supportIds: Array.from(new Set(superstructure.bearingSupportRelation.map((rel) => rel.supportId))),
    supportStationsM: extras.supportStationsM,
    supportSkewRads: extras.supportSkewRads,
    deckWidthM: superstructure.deck?.widthM.value,
    girderOffsetsM: Object.keys(girderOffsetsM).length > 0 ? girderOffsetsM : undefined,
    sourceReference: `superstructure:${superstructure.bridgeId}:rev-${superstructure.revisionId}`,
  };
}

function buildReconstructionEntries(facts: ReconstructionSampleFacts): BridgeProjectReconstruction["entries"] {
  const entries: NonNullable<BridgeProjectReconstruction["entries"]> = [
    {
      fieldKey: "bridgeLengthM",
      status: "CONFIRMED",
      value: facts.bridgeLengthM,
      unit: "m",
      derivationRef: facts.sourceReference,
    },
    ...facts.spanLengthsM.map((span, index) => ({
      fieldKey: `spanLengthsM[${index}]`,
      status: "CONFIRMED" as const,
      value: span,
      unit: "m",
      derivationRef: facts.sourceReference,
    })),
    ...facts.supportIds.map((id, index) => {
      const declared = facts.supportStationsM?.[index];
      const spanSum =
        index === 0
          ? 0
          : index === facts.supportIds.length - 1
            ? facts.bridgeLengthM
            : facts.spanLengthsM.slice(0, index).reduce((acc, s) => acc + s, 0);
      const station = declared ?? spanSum;
      return {
        fieldKey: `supportStationM.${id}`,
        status: declared !== undefined ? ("CONFIRMED" as const) : ("DERIVED" as const),
        value: station,
        unit: "m",
        derivationRef: declared !== undefined ? facts.sourceReference : "cumulative span sum",
      };
    }),
    ...facts.supportIds.map((id, index) => {
      const skew = facts.supportSkewRads?.[index];
      const finite = skew !== undefined && Number.isFinite(skew);
      return {
        fieldKey: `supportSkewRad.${id}`,
        status: finite ? ("CONFIRMED" as const) : ("DEFERRED" as const),
        ...(finite ? { value: skew, unit: "rad" } : {}),
        ...(!finite ? { stateReason: "skew not declared in superstructure sample" } : {}),
      };
    }),
    {
      fieldKey: "horizontalGeometry",
      status: "INFERRED",
      value: "straight",
      stateReason:
        "no horizontal curve/radius data in superstructure sample; reconstructed as a single straight",
    },
    {
      fieldKey: "verticalProfile",
      status: "MISSING",
      stateReason: "no vertical profile in superstructure sample",
    },
    {
      fieldKey: "crossfall",
      status: "MISSING",
      stateReason: "no crossfall data in superstructure sample",
    },
    ...(facts.deckWidthM !== undefined
      ? [{ fieldKey: "deckWidthM", status: "CONFIRMED" as const, value: facts.deckWidthM, unit: "m", derivationRef: facts.sourceReference }]
      : [{ fieldKey: "deckWidthM", status: "MISSING" as const, stateReason: "no deck width in superstructure sample" }]),
    ...Object.entries(facts.girderOffsetsM ?? {}).map(([id, offset]) => ({
      fieldKey: `girderOffsetM.${id}`,
      status: "CONFIRMED" as const,
      value: offset,
      unit: "m",
      derivationRef: facts.sourceReference,
    })),
  ];
  return entries;
}

/**
 * Reconstruct a partial road alignment from superstructure sample facts.
 * Deterministic: identical facts produce identical output.
 */
export function reconstructAlignmentFromSample(
  facts: ReconstructionSampleFacts,
  options: ReconstructionOptions = {},
): ReconstructionResult {
  // Cycle guard: reject a ①→②→① self-loop.
  if (options.generatingBridgeId !== undefined && options.generatingBridgeId === facts.bridgeId) {
    throw new BridgeProjectAdapterError(
      BP_CODES.SOURCE_INVALID,
      `Reconstruction cycle rejected: sample ${facts.bridgeId} was generated by the target alignment itself.`,
    );
  }

  assertFinite(facts.bridgeLengthM, "bridgeLengthM");
  if (facts.bridgeLengthM <= 0) {
    throw new BridgeProjectAdapterError(
      BP_CODES.SOURCE_INVALID,
      "bridgeLengthM must be positive for reconstruction.",
    );
  }
  if (facts.supportIds.length === 0) {
    throw new BridgeProjectAdapterError(
      BP_CODES.BRIDGE_EXTENT_MISSING,
      "Reconstruction requires at least one support id.",
    );
  }
  if (facts.spanLengthsM.length > 0) {
    const sum = facts.spanLengthsM.reduce((acc, s) => acc + s, 0);
    if (Math.abs(sum - facts.bridgeLengthM) > 1e-6) {
      throw new BridgeProjectAdapterError(
        BP_CODES.SPAN_SUM_MISMATCH,
        `Reconstruction span sum ${sum} does not equal bridge length ${facts.bridgeLengthM}.`,
      );
    }
  }

  const stations =
    facts.supportStationsM !== undefined && facts.supportStationsM.length === facts.supportIds.length
      ? facts.supportStationsM
      : facts.supportIds.map((_, i) =>
          i === 0
            ? 0
            : i === facts.supportIds.length - 1
              ? facts.bridgeLengthM
              : facts.spanLengthsM.slice(0, i).reduce((acc, s) => acc + s, 0),
        );
  assertAscendingStations(stations, "reconstruction support stations");

  const piers: PierDraft[] = facts.supportIds.map((id, i) => ({
    id,
    physicalDistance: roundStation(stations[i]!),
    kind: i === 0 || i === facts.supportIds.length - 1 ? ("abutment" as const) : ("pier" as const),
  }));
  const spans: SpanDraft[] = piers.slice(0, -1).map((pier, i) => ({
    id: `SPAN-${i + 1}`,
    startPhysicalDistance: pier.physicalDistance,
    endPhysicalDistance: piers[i + 1]!.physicalDistance,
    pierIdStart: pier.id,
    pierIdEnd: piers[i + 1]!.id,
  }));

  const draft: BuildIntermediateInput = {
    alignment: {
      id: options.alignmentId ?? `ALN-RECON-${facts.bridgeId}`,
      linerModelId: `reconstructed-${facts.bridgeId}`,
      coordinatePolicyId: "global",
      elements: [
        {
          type: "straight",
          id: "L1",
          start: { x: 0, y: 0 },
          azimuth: 0,
          // Cover the highest declared support station (or the bridge length when
          // no global stations are known) so every support is within range.
          length: stations.length > 0 ? Math.max(...stations) : facts.bridgeLengthM,
        },
      ],
    },
    stationDefinition: { originDisplayedStation: 0, interval: 10 },
    z: 0,
    piers,
    spans,
  };

  const alignment = buildBridgeProjectAlignment(draft, {
    alignmentId: options.alignmentId,
  });

  return {
    draft,
    alignment,
    reconstruction: {
      source: {
        documentKind: "bridge-superstructure-design",
        documentId: deriveStableUuid("bridge-project.reconstruction.source", facts.sourceReference),
        revisionId: 1 as never,
        contentChecksum: { algorithm: "sha256", hexDigest: "0".repeat(64) },
      },
      entries: buildReconstructionEntries(facts),
    },
  };
}
