import type { FieldMappingRow } from "./types";

export const FIELD_MAPPING_ROWS: FieldMappingRow[] = [
  {
    source_field: "主桁支間長",
    source_document: "SRC-DESIGN-CALC",
    normalized_field: "span.girder_span_length",
    normalized_unit: "m",
    notes: "mm source normalized to m",
  },
  {
    source_field: "主桁格間長",
    source_document: "SRC-DESIGN-CALC",
    normalized_field: "girder_panel_length",
    normalized_unit: "m",
    notes: "mm source normalized to m",
  },
  {
    source_field: "主桁格点座標 X",
    source_document: "SRC-DESIGN-CALC",
    normalized_field: "girder_point.x",
    normalized_unit: "m",
    notes: "mm source normalized to m",
  },
  {
    source_field: "主桁格点座標 Y",
    source_document: "SRC-DESIGN-CALC",
    normalized_field: "girder_point.y",
    normalized_unit: "m",
    notes: "mm source normalized to m",
  },
  {
    source_field: "横断間隔長",
    source_document: "SRC-DESIGN-CALC",
    normalized_field: "transverse_spacing",
    normalized_unit: "m",
    notes: "mm source normalized to m",
  },
  {
    source_field: "床版張出し長(法線方向)",
    source_document: "SRC-DESIGN-CALC",
    normalized_field: "overhang.normal",
    normalized_unit: "m",
    notes: "mm source normalized to m",
  },
  {
    source_field: "曲率(主桁中心)",
    source_document: "SRC-DESIGN-CALC",
    normalized_field: "curvature_radius",
    normalized_unit: "m",
    notes: "radius in m",
  },
  {
    source_field: "要素長",
    source_document: "SRC-LINER-SAMPLE",
    normalized_field: "horizontal_alignment.element_length",
    normalized_unit: "m",
    notes: "m source",
  },
  {
    source_field: "曲率半径",
    source_document: "SRC-LINER-SAMPLE",
    normalized_field: "horizontal_alignment.radius",
    normalized_unit: "m",
    notes: "m source",
  },
  {
    source_field: "測点",
    source_document: "SRC-LINER-SAMPLE",
    normalized_field: "station.meters",
    normalized_unit: "m",
    notes: "No.XX+YY converted to m",
  },
  {
    source_field: "クラウン高",
    source_document: "SRC-LINER-SAMPLE",
    normalized_field: "vertical_profile.crown_height",
    normalized_unit: "m",
    notes: "m source",
  },
  {
    source_field: "前/後勾配",
    source_document: "SRC-LINER-SAMPLE",
    normalized_field: "vertical_profile.grade",
    normalized_unit: "percent",
    notes: "percent source",
  },
  {
    source_field: "横断勾配",
    source_document: "SRC-LINER-SAMPLE",
    normalized_field: "crossfall.grade",
    normalized_unit: "percent",
    notes: "percent source",
  },
  {
    source_field: "計画高",
    source_document: "SRC-LINER-SAMPLE",
    normalized_field: "section_height.plan_height",
    normalized_unit: "m",
    notes: "m source",
  },
  {
    source_field: "舗装厚 H1",
    source_document: "SRC-LINER-SAMPLE",
    normalized_field: "hoso.thickness",
    normalized_unit: "m",
    notes: "m source",
  },
  {
    source_field: "ハンチ高 H3",
    source_document: "SRC-LINER-SAMPLE",
    normalized_field: "haunch.height",
    normalized_unit: "m",
    notes: "m source",
  },
  {
    source_field: "主桁高 H4",
    source_document: "SRC-LINER-SAMPLE",
    normalized_field: "section_height.girder_height",
    normalized_unit: "m",
    notes: "m source",
  },
  {
    source_field: "平均支間長",
    source_document: "SRC-DRAWING",
    normalized_field: "span.average",
    normalized_unit: "m",
    notes: "mm source normalized to m",
  },
  {
    source_field: "主桁間隔",
    source_document: "SRC-DRAWING",
    normalized_field: "girder_span_length.spacing",
    normalized_unit: "m",
    notes: "mm source normalized to m",
  },
  {
    source_field: "アスファルト舗装 t",
    source_document: "SRC-DRAWING",
    normalized_field: "hoso.thickness",
    normalized_unit: "m",
    notes: "mm source normalized to m",
  },
];
