export type {
  BridgeDefinition,
  BridgeDefinitionAlignmentRef,
  BridgeDefinitionBearing,
  BridgeDefinitionCoordinatePolicy,
  BridgeDefinitionCrossBeam,
  BridgeDefinitionDeck,
  BridgeDefinitionGenerationSettings,
  BridgeDefinitionGirder,
  BridgeDefinitionLoad,
  BridgeDefinitionLoadTarget,
  BridgeDefinitionMetadata,
  BridgeDefinitionSchemaVersion,
  BridgeDefinitionSource,
  BridgeDefinitionSpan,
  BridgeDefinitionStation,
  BridgeDefinitionSuperstructure,
  BridgeDefinitionSuperstructureKind,
  BridgeDefinitionSupport,
} from "./types";

export { BRIDGE_DEFINITION_SCHEMA_VERSION_LITERAL } from "./types";

export {
  createBridgeDefinitionFromLinerBridge,
  validateLinerBridgeForBridgeDefinition,
} from "./adapters/fromLinerBridge";

export type { LinerBridgeToBridgeDefinitionOptions } from "./adapters/fromLinerBridge";

export {
  createBridgeDefinitionFromBridgeProject,
  validateBridgeProjectForBridgeDefinition,
} from "./adapters/fromBridgeProject";

export type { BridgeProjectToBridgeDefinitionOptions } from "./adapters/fromBridgeProject";

export {
  createStructuralModelFromBridgeDefinition,
  validateBridgeDefinitionForStructuralModel,
  generateStructuralModel,
  generateStructuralModelFromLinerBridge,
} from "./generator";

export type {
  BridgeDefinitionStructuralModelDiagnostic,
  BridgeDefinitionStructuralModelOptions,
  StructuralModelGenerationResult,
} from "./generator";

export {
  DEFAULT_SEMANTIC_TOLERANCE,
  angleWithinTolerance,
  buildGeometryMetrics,
  buildTopologyMetrics,
  compareNormalizedModels,
  comparePropertyParity,
  compareScalarWithTolerance,
  compareGeneratedProjectModels,
  compareLegacyAndBridgeDefinitionModels,
  compareLoadParity,
  compareSemanticParity,
  createLegacyBridgeDefinitionSourceMeta,
  createLinerStructureOnlySourceMeta,
  createSemanticParityReportForGeneratedModels,
  generateBridgeDefinitionProjectModelFromBridgeProject,
  generateBridgeDefinitionProjectModelFromLinerBridge,
  SEMANTIC_PARITY_GOLDEN_GENERATED_AT,
  SEMANTIC_PARITY_TOOL_VERSION,
  serializeSemanticParityReportForGolden,
  compareSupportParity,
  computeGeometryMetrics,
  computeTopologyMetrics,
  createParityReportEnvelope,
  canonicalizeParityReportEnvelope,
  distance,
  distanceWithinTolerance,
  isNearEqualProperty,
  matchNormalizedMembers,
  matchNormalizedNodes,
  mergeSemanticTolerance,
  nearlyEqual,
  nearlyZero,
  normalizeProjectModelForSemanticParity,
  PARITY_REPORT_ENVELOPE_SCHEMA_VERSION,
  serializeParityReportEnvelope,
  validateStructuralModel,
} from "./semanticParity";

export type {
  AmbiguousMatch,
  BoundingBox3,
  CompareGeneratedProjectModelsOptions,
  CompareSemanticParityOptions,
  CreateSemanticParityReportOptions,
  GeneratedProjectModelSourceMeta,
  CreateParityReportEnvelopeOptions,
  CanonicalizeParityReportEnvelopeOptions,
  DegreeHistogram,
  GeometryMetrics,
  JsonSafeValue,
  LengthStats,
  LoadParitySummary,
  MatchDiagnostics,
  MatchResult,
  MatchedPair,
  NormalizedLoadCase,
  NormalizedMaterial,
  NormalizedMember,
  NormalizedMemberLoad,
  NormalizedModel,
  NormalizedNode,
  NormalizedNodalLoad,
  NormalizedSection,
  NormalizedSupport,
  NodalLoadVector,
  MemberLoadVector,
  ParityMetrics,
  ParityMismatch,
  ParityReport,
  ParityReportEnvelope,
  ParityReportSource,
  ParityReportSummary,
  PropertyParitySummary,
  SemanticParityDiagnostic,
  SemanticParitySeverity,
  SemanticParitySource,
  SemanticParityStatus,
  SemanticTolerance,
  SerializeParityReportEnvelopeOptions,
  StructuralValidationSummary,
  SupportParitySummary,
  ToleranceBand,
  TopologyMetrics,
  TraceInfo,
  UnmatchedItem,
  Vector3,
} from "./semanticParity";
