export const IMPORTER_RENDER_CROSS_SECTION_BLOCKED =
  "IMPORTER_RENDER_CROSS_SECTION_BLOCKED" as const;

export const IMPORTER_RENDER_PLAN_PREVIEW_BLOCKED =
  "IMPORTER_RENDER_PLAN_PREVIEW_BLOCKED" as const;

export const IMPORTER_RENDER_EXPORT_BLOCKED =
  "IMPORTER_RENDER_EXPORT_BLOCKED" as const;

export const IMPORTER_RENDER_EXPORT_DEGRADED =
  "IMPORTER_RENDER_EXPORT_DEGRADED" as const;
