export {
  DOCUMENT_KINDS,
  isDocumentKind,
  type DocumentKind,
} from "./documentKind";

export {
  COORDINATE_CONTEXT_SCHEMA_VERSION,
  validateCoordinateContext,
  type AuthorityStatus,
  type AxisDirection,
  type AxisDirections,
  type AxisName,
  type AxisOrder,
  type CanonicalTransform,
  type CoordinateAngleUnit,
  type CoordinateContext,
  type CoordinateReferenceType,
  type DatumAuthority,
  type ElevationSignConvention,
  type Handedness,
  type OffsetSignConvention,
  type OrientationSpec,
  type Point3,
  type RotationConvention,
  type RotationOrder,
  type StationConvention,
  type TransformMatrix4x4,
  type UncertainCanonicalTransform,
  type ValidateCoordinateContextOptions,
  type VerifiedCanonicalTransform,
  type VerticalAxis,
} from "./coordinateContext";

export { isIso8601UtcTimestamp } from "./isoTimestamp";

export {
  asSchemaId,
  asSchemaVersion,
  isSemVerString,
  parseSchemaId,
  parseSchemaVersion,
  requireSchemaId,
  requireSchemaVersion,
  validateSchemaIdentity,
  type SchemaId,
  type SchemaIdentity,
  type SchemaVersion,
} from "./schemaIdentity";

export {
  asRevisionId,
  isPositiveRevisionId,
  requireRevisionId,
  REVISION_METADATA_SCHEMA_VERSION,
  validateRevisionMetadata,
  type RevisionId,
  type RevisionMetadata,
} from "./revision";

export {
  validateProvenance,
  type ActorRef,
  type ActorType,
  type Provenance,
  type ToolProvenance,
} from "./provenance";

export {
  asStableIdNamespace,
  createStableEntityId,
  getDisplayAliases,
  parseStableIdNamespace,
  parseStableUuid,
  requireStableIdNamespace,
  stableEntityIdEquals,
  validateStableEntityId,
  withDisplayAlias,
  type CreateStableEntityIdInput,
  type DisplayAlias,
  type StableEntityId,
  type StableEntityIdInput,
  type StableIdNamespace,
} from "./stableEntityId";

export {
  UNIT_CONTEXT_SCHEMA_VERSION,
  validateUnitContext,
  type AngleUnit,
  type AreaUnit,
  type CrossfallSignConvention,
  type ForceUnit,
  type InertiaUnit,
  type LengthUnit,
  type MassUnit,
  type ModulusUnit,
  type MomentUnit,
  type RotationSignConvention,
  type StressUnit,
  type TemperatureUnit,
  type TimeUnit,
  type UnitContext,
  type UnitContextValidationProfile,
  type UnitSignConventions,
  type ValidateUnitContextOptions,
} from "./unitContext";

export {
  createValidationIssue,
  createValidationResult,
  deriveValidationStatus,
  hasValidationErrors,
  mergeValidationResults,
  VALIDATION_RESULT_SCHEMA_VERSION,
  type CreateValidationIssueInput,
  type ValidationIssue,
  type ValidationResult,
  type ValidationSeverity,
  type ValidationStatus,
} from "./validation";

export {
  generateUuid,
  isValidUuid,
  parseUuid,
  UuidGenerationUnavailableError,
  type RandomBytesSource,
  type UuidString,
} from "./uuid";

export {
  contentChecksumsEqual,
  CONTENT_CHECKSUM_ALGORITHM,
  isSha256HexDigest,
  parseContentChecksum,
  SHA256_HEX_LOWERCASE_PATTERN,
  validateContentChecksum,
  type ContentChecksum,
  type ContentChecksumAlgorithm,
} from "./contentChecksum";

export {
  CAPABILITY_STATES,
  isCapabilityState,
  validateCapabilityBlock,
  type CapabilityBlock,
  type CapabilityState,
} from "./capabilityBlock";

export {
  BRIDGE_FRAME_ANALYSIS_DOCUMENT_KIND,
  detectForbiddenFrameRoadOrViewerKeys,
  validateBridgeFrameAnalysisDocument,
  type AnalysisSettings,
  type BridgeFrameAnalysisDocument,
  type FrameMaterialEntry,
  type FrameMemberEntry,
  type FrameNodeEntry,
  type FrameSectionEntry,
  type FrameSupportEntry,
  type LoadDefinitionEntry,
  type LoadKind,
  type StructuralModel,
  type TransferBinding,
} from "./bridgeFrameAnalysisDocument";

export {
  BRIDGE_SUPERSTRUCTURE_DESIGN_DOCUMENT_KIND,
  DECK_ANCHORAGE_ROLES,
  DESIGN_ENTITY_DESIGN_STATUSES,
  isDesignEntityDesignStatus,
  validateBridgeSuperstructureDesignDocument,
  type BraceMember,
  type BridgeSuperstructureDesignDocument,
  type BsddAnalysisBinding,
  type BsddBridge,
  type BsddDeck,
  type BsddGirderLine,
  type BsddLifecycleStatus,
  type BsddLoad,
  type BsddLoadCase,
  type BsddMaterialDefinition,
  type BsddPhase1ScopeAssertion,
  type BsddProjectContext,
  type BsddSpan,
  type BsddSupport,
  type BsddValidationStatus,
  type CrossBeam,
  type DeckAnchorage,
  type DeckAnchorageRole,
  type DesignAnalysisMemberMapping,
  type DesignBindingStatus,
  type DesignEntityAdoptionStatus,
  type DesignEntityDesignStatus,
  type DesignEntityMetadata,
  type DesignGeometryReference,
  type GirderSectionSegment,
  type Haunch,
  type LateralBracing,
  type MainGirder,
  type RcDeck,
  type SdmNonCompositeAssertion,
  type Splice,
  type Stiffener,
  type StructuralDesignModel,
  type StructuralDesignModelEntity,
  type SwayBracing,
  type ValidateBridgeSuperstructureDesignDocumentOptions,
} from "./bridgeSuperstructureDesignDocument";

export {
  adoptionStatusToNumericAuthority,
  governedQuantityToNumericRecord,
  isGovernedQuantityAdoptionStatus,
  validateGovernedQuantity,
  GOVERNED_QUANTITY_ADOPTION_STATUSES,
  type GovernedQuantity,
  type GovernedQuantityAdoptionStatus,
  type ValidateGovernedQuantityOptions,
} from "./governedQuantity";

export {
  COMMON_ENVELOPE_SHAPE_ID,
  BRIDGE_FRAME_ANALYSIS_DOCUMENT_SCHEMA_ID,
  BRIDGE_FRAME_ANALYSIS_DOCUMENT_SCHEMA_VERSION,
  BRIDGE_SUPERSTRUCTURE_DESIGN_DOCUMENT_SCHEMA_ID,
  BRIDGE_SUPERSTRUCTURE_DESIGN_DOCUMENT_SCHEMA_VERSION,
  FRAME_ANALYSIS_RESULT_RESOURCE_SCHEMA_ID,
  FRAME_ANALYSIS_RESULT_RESOURCE_SCHEMA_VERSION,
  CONTRACT_VERSION_SUPPORT_MATRIX,
  DOCUMENT_REFERENCE_SCHEMA_ID,
  ENGINEERING_PROJECT_SCHEMA_ID,
  ENGINEERING_PROJECT_SCHEMA_VERSION,
  ROAD_DESIGN_DOCUMENT_SCHEMA_ID,
  ROAD_DESIGN_DOCUMENT_SCHEMA_VERSION,
  ROAD_TO_FRAME_TRANSFER_PACKAGE_SCHEMA_ID,
  ROAD_TO_FRAME_TRANSFER_PACKAGE_SCHEMA_VERSION,
  TRANSFER_RECORD_SCHEMA_ID,
  TRANSFER_RECORD_SCHEMA_VERSION,
  getContractVersionSupport,
  isSupportedContractVersion,
  MIGRATION_RECORD_SCHEMA_ID,
  MIGRATION_RECORD_SCHEMA_VERSION,
  UNKNOWN_FIELD_STORE_SCHEMA_ID,
  UNKNOWN_FIELD_STORE_SCHEMA_VERSION,
  validateSupportedContractVersion,
  type ContractVersionSupport,
} from "./contractVersionRegistry";

export {
  FRAME_ANALYSIS_LOAD_CONTEXT_KINDS,
  FRAME_ANALYSIS_RESULT_KINDS,
  FRAME_ANALYSIS_RESULT_STATUSES,
  isFrameAnalysisResultResource,
  validateFrameAnalysisResultResource,
  type FrameAnalysisLoadContext,
  type FrameAnalysisLoadContextEntry,
  type FrameAnalysisLoadContextKind,
  type FrameAnalysisNumericValueMap,
  type FrameAnalysisResultDiagnostic,
  type FrameAnalysisResultKind,
  type FrameAnalysisResultPayloadCatalog,
  type FrameAnalysisResultPayloadEntry,
  type FrameAnalysisResultResource,
  type FrameAnalysisResultRow,
  type FrameAnalysisResultStatus,
} from "./frameAnalysisResultResource";

export {
  validateCommonEnvelope,
  type CommonEnvelope,
  type ValidateCommonEnvelopeOptions,
} from "./commonEnvelope";

export {
  documentReferenceIdentity,
  validateDocumentReference,
  validateDocumentReferenceCollection,
  type DocumentReference,
  type DocumentReferenceIdentity,
} from "./documentReference";

export {
  detectForbiddenEmbeddedPayloadKeys,
  ENGINEERING_PROJECT_DOCUMENT_KIND,
  validateEngineeringProject,
  type EngineeringProject,
} from "./engineeringProject";

export {
  BRIDGE_PROJECT_DOCUMENT_KIND,
  detectForbiddenEmbeddedPayloadKeys as detectForbiddenBridgeProjectPayloadKeys,
  validateBridgeProject,
  type BridgeProject,
  type BridgeProjectOwner,
  type BridgeProjectReaction,
  type BridgeProjectReconstruction,
  type BridgeProjectReconstructionEntry,
  type BridgeProjectReferences,
  type BridgeProjectSectionStatus,
  type BridgeProjectSupport,
  type BridgeProjectValue,
  type BridgeProjectValueStatus,
} from "./bridgeProject";

export {
  EXTENSION_KEY_PATTERN,
  isExtensionKey,
  validateExtensions,
  type ExtensionValue,
  type Extensions,
} from "./extensions";

export {
  MIGRATION_RECORD_DOCUMENT_KIND,
  validateMigrationRecord,
  type MappingDisposition,
  type MigrationIdMapping,
  type MigrationRecord,
  type MigrationStatus,
} from "./migrationRecord";

export {
  detectForbiddenRoadFrameMechanicsKeys,
  ROAD_DESIGN_DOCUMENT_KIND,
  validateRoadDesignDocument,
  type RoadAlignmentEntry,
  type RoadBridgeEntry,
  type RoadCrossSectionEntry,
  type RoadDesignDocument,
  type RoadProfileEntry,
  type RoadStationing,
  type RoadStationingEntry,
} from "./roadDesignDocument";

export {
  validatePackageArtifactReference,
  validatePolicyReference,
  validateTransferRecordArtifactReference,
  type PackageArtifactReference,
  type PolicyReference,
  type TransferRecordArtifactReference,
} from "./artifactReference";

export { deepFreeze } from "./deepFreeze";

export {
  validatePolygon3,
  validatePolyline3,
  type Polygon3,
  type Polyline3,
} from "./geometryPrimitives";

export {
  PACKAGE_CAPABILITY_STATES,
  isApplyBlockingCapabilityState,
  isPackageCapabilityState,
  validateCapabilityAssessmentSummary,
  validatePackageCapabilityCollection,
  validatePackageCapabilityEntry,
  type CapabilityAssessmentSummary,
  type PackageCapabilityEntry,
  type PackageCapabilityState,
} from "./packageCapability";

export {
  assessPackageApplyability,
  detectForbiddenTransferPackageKeys,
  validateRoadToFrameTransferPackage,
  validateRoadToFrameTransferPackageInput,
  ROAD_TO_FRAME_TRANSFER_PACKAGE_KIND,
  type AlignmentRefEntry,
  type BearingLineEntry,
  type CrossBeamCandidateEntry,
  type LoadPlacementCandidateEntry,
  type MainGirderCandidateEntry,
  type PackageApplyabilityResult,
  type RoadRegionEntry,
  type RoadToFrameTransferPackage,
  type SpanEndpointRef,
  type SpanEntry,
  type StationRefEntry,
  type SubstructureEntry,
  type SurfaceRegionEntry,
  type TransferPackageGeometry,
} from "./roadToFrameTransferPackage";

export {
  validateTransferRecord,
  validateTransferCapabilityAssessmentCollection,
  validateTransferCapabilityAssessmentEntry,
  TRANSFER_RECORD_KIND,
  type EntityMappingDisposition,
  type EntityMappingEntry,
  type TransferCapabilityAssessmentEntry,
  type TransferDecisionEntry,
  type TransferRecord,
  type TransferRecordStatus,
} from "./transferRecord";

export {
  UNKNOWN_FIELD_STORE_DOCUMENT_KIND,
  validateUnknownFieldStore,
  type SourceVersionClassification,
  type UnknownFieldCollisionRecord,
  type UnknownFieldCriticality,
  type UnknownFieldEntry,
  type UnknownFieldStore,
} from "./unknownFieldStore";

export {
  validateImmutableResourceReference,
  type ImmutableResourceReference,
} from "./immutableResourceReference";

export {
  isJsonValue,
  validateJsonValue,
  type JsonValue,
} from "./jsonValue";

export {
  MIGRATION_ERROR_CODES,
  MigrationRegistry,
  asMigrationStepId,
  cloneMigrationValue,
  createMigrationAmbiguousPathError,
  createMigrationDuplicateStepError,
  createMigrationPathNotFoundError,
  createMigrationRegistry,
  createMigrationStepFailedError,
  createMigrationUnknownSourceVersionError,
  createMigrationUnknownTargetVersionError,
  createMigrationValidationFailedError,
  isMigrationAmbiguousPathError,
  isMigrationDuplicateStepError,
  isMigrationErrorCode,
  isMigrationPathNotFoundError,
  isMigrationStepFailedError,
  isMigrationValidationFailedError,
  resolveMigrationPath,
  type AppliedMigrationStep,
  type MappingDisposition as MigrationFrameworkMappingDisposition,
  type MigrationAmbiguousPathError,
  type MigrationClock,
  type MigrationDependencies,
  type MigrationDuplicateStepError,
  type MigrationError,
  type MigrationErrorCode,
  type MigrationGraphEdge,
  type MigrationIdGenerator,
  type MigrationPathError,
  type MigrationPathNotFoundError,
  type MigrationPathResolutionResult,
  type MigrationProvenanceNote,
  type MigrationRegisterResult,
  type MigrationReport,
  type MigrationReportStatus,
  type MigrationRequest,
  type MigrationResult,
  type MigrationStepExecutionContext,
  type MigrationStepFailedError,
  type MigrationStepFn,
  type MigrationStepId,
  type MigrationStepOutcome,
  type MigrationStepRegistration,
  type MigrationUnknownFieldNote,
  type MigrationUnknownSourceVersionError,
  type MigrationUnknownTargetVersionError,
  type MigrationValidationFailedError,
  type ResolvedMigrationEdge,
  type TargetValidator,
} from "./migration";

export {
  REPOSITORY_ERROR_CODES,
  assertAppendOnlyRecordRepository,
  cloneArtifact,
  createAppendOnlyRecordRepository,
  createBridgeFrameAnalysisDocumentRepository,
  createImmutablePackageRepository,
  createInMemoryBridgeFrameAnalysisDocumentRepository,
  createInMemoryRoadDesignDocumentRepository,
  createInMemoryRoadToFrameTransferPackageRepository,
  createInMemoryTransferRecordRepository,
  createRepositoryAlreadyExistsError,
  createRepositoryAppendOnlyViolationError,
  createRepositoryImmutableResourceError,
  createRepositoryNotFoundError,
  createRepositoryRevisionConflictError,
  createRepositoryValidationFailedError,
  createRevisionedDocumentRepository,
  createRoadDesignDocumentRepository,
  createRoadToFrameTransferPackageRepository,
  createTransferRecordRepository,
  isRepositoryAlreadyExistsError,
  isRepositoryAppendOnlyViolationError,
  isRepositoryErrorCode,
  isRepositoryImmutableResourceError,
  isRepositoryNotFoundError,
  isRepositoryRevisionConflictError,
  isRepositoryValidationFailedError,
  repositoryFailure,
  repositorySuccess,
  runRepositoryFaultInjection,
  type AppendDocumentRevisionRequest,
  type AppendOnlyRecordEnvelope,
  type AppendOnlyRecordRepository,
  type AppendOnlyRecordRepositoryOptions,
  type AppendOnlyRecordValidateOutcome,
  type BridgeFrameAnalysisDocumentRepository,
  type ImmutablePackageEnvelope,
  type ImmutablePackageRepository,
  type ImmutablePackageRepositoryOptions,
  type ImmutablePackageValidateOutcome,
  type PackageIdentity,
  type ReadDocumentRevisionRequest,
  type RepositoryAlreadyExistsError,
  type RepositoryAppendOnlyViolationError,
  type RepositoryError,
  type RepositoryErrorCode,
  type RepositoryFaultInjection,
  type RepositoryImmutableResourceError,
  type RepositoryNotFoundError,
  type RepositoryResult,
  type RepositoryRevisionConflictError,
  type RepositoryValidateOutcome,
  type RepositoryValidationFailedError,
  type RevisionedDocumentEnvelope,
  type RevisionedDocumentRepository,
  type RevisionedDocumentRepositoryOptions,
  type RoadDesignDocumentRepository,
  type RoadToFrameTransferPackageRepository,
  type TransferPackageIdentity,
  type TransferRecordRepository,
} from "./repository";

export {
  LEGACY_ADAPTER_ERROR_CODES,
  LEGACY_ADAPTER_VERSION,
  LEGACY_FRAME_ADAPTER_ID,
  LEGACY_FRAME_FORMAT_ID,
  LEGACY_ROAD_ADAPTER_ID,
  LEGACY_ROAD_FORMAT_ID,
  adaptLegacyFrameInput,
  adaptLegacyRoadInput,
  canonicalJsonForChecksum,
  classifyLegacyInput,
  cloneLegacyValue,
  computeContentChecksum,
  computeSha256Hex,
  createLegacyAmbiguousCoordinateError,
  createLegacyAmbiguousUnitError,
  createLegacyBrokenIdError,
  createLegacyInvalidShapeError,
  createLegacyMissingVersionError,
  createLegacyMixedOwnershipError,
  createLegacyUnresolvedReferenceError,
  createLegacyUnsupportedFormatError,
  createLegacyUnsupportedVersionError,
  createLegacyValidationFailedError,
  defaultLegacyAdapterClock,
  deriveStableUuid,
  isLegacyAdapterErrorCode,
  isLegacyFrameInput,
  isLegacyRoadInput,
  isPlainLegacyObject,
  type LegacyAdapterClock,
  type LegacyAdapterError,
  type LegacyAdapterErrorCode,
  type LegacyAdapterFailure,
  type LegacyAdapterOptions,
  type LegacyAdapterResult,
  type LegacyAdapterSuccess,
  type LegacyAmbiguousCoordinateError,
  type LegacyAmbiguousUnitError,
  type LegacyBrokenIdError,
  type LegacyFormatClassification,
  type LegacyFormatId,
  type LegacyFrameFormatId,
  type LegacyInvalidShapeError,
  type LegacyMissingVersionError,
  type LegacyMixedOwnershipError,
  type LegacyRoadFormatId,
  type LegacyUnresolvedReferenceError,
  type LegacyUnsupportedFormatError,
  type LegacyUnsupportedVersionError,
  type LegacyValidationFailedError,
} from "./legacy";

export {
  PERSISTENCE_ERROR_CODES,
  checksumForSerializedDocument,
  createDocumentPersistenceGateway,
  createInMemoryAtomicJsonStore,
  createPersistenceAdapterFailedError,
  createPersistenceLegacyWriteForbiddenError,
  createPersistenceMalformedJsonError,
  createPersistenceMigrationFailedError,
  createPersistenceMissingVersionError,
  createPersistenceStoreFailedError,
  createPersistenceUnsupportedFormatError,
  createPersistenceUnsupportedVersionError,
  createPersistenceValidationFailedError,
  isTargetFrameDocument,
  isTargetRoadDocument,
  loadBridgeFrameAnalysisDocument,
  loadRoadDesignDocument,
  normalizeRawInput,
  parseRawJson,
  saveBridgeFrameAnalysisDocument,
  saveRoadDesignDocument,
  serializeTargetDocument,
  type AtomicJsonStorePort,
  type DocumentLoadFailure,
  type DocumentLoadResult,
  type DocumentLoadSourceKind,
  type DocumentLoadSuccess,
  type DocumentPersistenceGateway,
  type DocumentPersistenceGatewayOptions,
  type DocumentSaveFailure,
  type DocumentSaveResult,
  type DocumentSaveSuccess,
  type LoadDocumentDependencies,
  type PersistenceAdapterFailedError,
  type PersistenceError,
  type PersistenceErrorCode,
  type PersistenceLegacyWriteForbiddenError,
  type PersistenceMalformedJsonError,
  type PersistenceMigrationFailedError,
  type PersistenceMissingVersionError,
  type PersistenceStoreFailedError,
  type PersistenceUnsupportedFormatError,
  type PersistenceUnsupportedVersionError,
  type PersistenceValidationFailedError,
} from "./persistence";

export {
  CONTRACT_JSON_SCHEMA_DEFINITIONS,
  CONTRACT_JSON_SCHEMA_SEMANTIC_METADATA,
  CONTRACT_SCHEMA_ID_BASE,
  SHARED_CONTRACT_VERSION,
  contractJsonSchemaPath,
  contractSchemaId,
  coordinateContextSchema,
  generateAllContractJsonSchemas,
  generateContractJsonSchema,
  jsonSchemaSemanticallyEqual,
  normalizeJsonSchema,
  parseBridgeFrameAnalysisDocumentValue,
  parseBridgeSuperstructureDesignDocumentValue,
  parseCommonEnvelopeValue,
  parseContentChecksumValue,
  parseContractValue,
  parseCoordinateContextValue,
  parseDocumentReferenceValue,
  parseEngineeringProjectValue,
  parseMigrationRecordValue,
  parseProvenanceValue,
  parseRoadDesignDocumentValue,
  parseRoadToFrameTransferPackageValue,
  parseTransferRecordValue,
  parseRevisionMetadataValue,
  parseSchemaIdentityValue,
  parseStableEntityIdValue,
  parseUnitContextValue,
  parseUnknownFieldStoreValue,
  parseUuidValue,
  parseValidationResultValue,
  provenanceSchema,
  roadDesignDocumentSchema,
  roadToFrameTransferPackageSchema,
  transferRecordSchema,
  revisionMetadataSchema,
  schemaIdentitySchema,
  stableEntityIdSchema,
  unitContextSchema,
  unknownFieldStoreSchema,
  uuidValueSchema,
  validationIssueSchema,
  validationResultSchema,
  validContractValidationResult,
  zodIssueToValidationIssue,
  zodIssuesToValidationResult,
  bridgeFrameAnalysisDocumentSchema,
  bridgeSuperstructureDesignDocumentSchema,
  governedQuantitySchema,
  commonEnvelopeSchema,
  createCommonEnvelopeSchema,
  contentChecksumSchema,
  documentReferenceSchema,
  engineeringProjectSchema,
  migrationRecordSchema,
  bridgeProjectSchema,
  type BridgeFrameAnalysisDocumentValue,
  type BridgeSuperstructureDesignDocumentValue,
  type GovernedQuantityValue,
  type CommonEnvelopeValue,
  type ContentChecksumValue,
  type CreateCommonEnvelopeSchemaOptions,
  type ContractJsonSchemaDefinition,
  type ContractJsonSchemaSemanticMetadata,
  type ContractParseFailure,
  type ContractParseResult,
  type ContractParseSuccess,
  type CoordinateContextValue,
  type DocumentReferenceValue,
  type EngineeringProjectValue,
  type GeneratedContractJsonSchema,
  type MigrationRecordValue,
  type ProvenanceValue,
  type RoadDesignDocumentValue,
  type RoadToFrameTransferPackageValue,
  type TransferRecordValue,
  type RevisionMetadataValue,
  type SchemaIdentityValue,
  type SemanticValidationOptions,
  type BridgeProjectValue as BridgeProjectRuntimeValue,
  type StableEntityIdValue,
  type UnitContextValue,
  type UnknownFieldStoreValue,
  type UuidValue,
  type ValidationResultValue,
} from "./runtime";
