export const IMPORTER_CUM_DISTANCE_CHAIN_INVALID = "IMPORTER_CUM_DISTANCE_CHAIN_INVALID";
export const IMPORTER_CUM_WIDTH_CHAIN_INVALID = "IMPORTER_CUM_WIDTH_CHAIN_INVALID";
export const IMPORTER_AZIMUTH_JUMP = "IMPORTER_AZIMUTH_JUMP";
export const IMPORTER_SYMMETRY_WIDTH_MISMATCH = "IMPORTER_SYMMETRY_WIDTH_MISMATCH";
export const IMPORTER_STATION_NOT_MONOTONIC = "IMPORTER_STATION_NOT_MONOTONIC";
export const IMPORTER_PROFILE_GRADE_MISMATCH = "IMPORTER_PROFILE_GRADE_MISMATCH";
export const IMPORTER_NOT_COMPUTED_FLAG_MISMATCH = "IMPORTER_NOT_COMPUTED_FLAG_MISMATCH";
export const IMPORTER_SOURCE_REF_MISSING = "IMPORTER_SOURCE_REF_MISSING";
export const IMPORTER_COORDINATE_SYSTEM_MISSING = "IMPORTER_COORDINATE_SYSTEM_MISSING";
export const IMPORTER_LINE_MASTER_MISMATCH = "IMPORTER_LINE_MASTER_MISMATCH";
export const IMPORTER_CROSS_SLOPE_INCONSISTENT = "IMPORTER_CROSS_SLOPE_INCONSISTENT";
export const IMPORTER_EXPORT_PLAN_MISSING = "IMPORTER_EXPORT_PLAN_MISSING";

export {
  IMPORTER_RENDER_CROSS_SECTION_BLOCKED,
  IMPORTER_RENDER_PLAN_PREVIEW_BLOCKED,
  IMPORTER_RENDER_EXPORT_BLOCKED,
  IMPORTER_RENDER_EXPORT_DEGRADED,
} from "../diagnostics";
