import type {
  DiagnosticLevel,
  LinerDiagnosticCode,
  ValidationIssue,
} from "./types";

export const LINER_DIAGNOSTIC_CODES = {
  zeroLengthSegment: "LINER_GEOM_ZERO_LENGTH_SEGMENT",
  positionDiscontinuity: "LINER_GEOM_POSITION_DISCONTINUITY",
  azimuthDiscontinuity: "LINER_GEOM_AZIMUTH_DISCONTINUITY",
  clothoidInvalidRadius: "LINER_GEOM_CLOTHOID_INVALID_RADIUS",
  clothoidAccuracyExceeded: "LINER_GEOM_CLOTHOID_ACCURACY_EXCEEDED",
  clothoidLongSpiral: "LINER_GEOM_CLOTHOID_LONG_SPIRAL",
  inverseProjectionFailed: "LINER_GEOM_INVERSE_PROJECTION_FAILED",
  duplicateStationEquation: "LINER_STATION_DUPLICATE_EQUATION",
  stationOutOfRange: "LINER_STATION_OUT_OF_RANGE",
  gridSpacingInvalid: "LINER_GRID_SPACING_INVALID",
  missingFrameNode: "LINER_FRAME_MISSING_NODE",
  missingFrameSection: "LINER_FRAME_MISSING_SECTION",
  zeroLengthMember: "LINER_FRAME_ZERO_LENGTH_MEMBER",
  disconnectedFrame: "LINER_FRAME_DISCONNECTED",
  duplicateFrameId: "LINER_FRAME_DUPLICATE_ID",
  invalidFrameSchema: "LINER_FRAME_SCHEMA_INVALID",
  profileElevationDiscontinuity: "LINER_PROFILE_ELEVATION_DISCONTINUITY",
  profileGradeDiscontinuity: "LINER_PROFILE_GRADE_DISCONTINUITY",
  profileCoverageGap: "LINER_PROFILE_COVERAGE_GAP",
  profileAdjacencyGap: "LINER_PROFILE_ADJACENCY_GAP",
  profileEndCoverageGap: "LINER_PROFILE_END_COVERAGE_GAP",
  profileOverlap: "LINER_PROFILE_OVERLAP",
  profileGradeExceedsLimit: "LINER_PROFILE_GRADE_EXCEEDS_LIMIT",
  spanEndExceedsAlignment: "LINER_SPAN_END_EXCEEDS_ALIGNMENT",
  originStationAmbiguous: "LINER_ORIGIN_STATION_AMBIGUOUS",
  profileParabolicZMergeDeferred: "LINER_PROFILE_PARABOLIC_Z_MERGE_DEFERRED",
  crossfallIntervalOverlap: "LINER_CROSSFALL_INTERVAL_OVERLAP",
  crossfallIntervalInvalidRange: "LINER_CROSSFALL_INTERVAL_INVALID_RANGE",
  crossfallPivotChangeUnsupported: "LINER_CROSSFALL_PIVOT_CHANGE_UNSUPPORTED",
  crossfallMeasuredGridPrecedence: "LINER_CROSSFALL_MEASURED_GRID_PRECEDENCE",
  widthChangePointOverlap: "LINER_WIDTH_CHANGE_POINT_OVERLAP",
  widthChangePointOutOfRange: "LINER_WIDTH_CHANGE_POINT_OUT_OF_RANGE",
  widthChangePointInvalid: "LINER_WIDTH_CHANGE_POINT_INVALID",
  crossSectionTemplateDuplicateId: "LINER_CROSS_SECTION_TEMPLATE_DUPLICATE_ID",
  crossSectionTemplateMissingId: "LINER_CROSS_SECTION_TEMPLATE_MISSING_ID",
  crossSectionOffsetLineDuplicateId: "LINER_CROSS_SECTION_OFFSET_LINE_DUPLICATE_ID",
  crossSectionOffsetLineMissingId: "LINER_CROSS_SECTION_OFFSET_LINE_MISSING_ID",
  crossSectionOffsetLineMissing: "LINER_CROSS_SECTION_OFFSET_LINE_MISSING",
  crossSectionGridDefinitionDuplicateId: "LINER_CROSS_SECTION_GRID_DEFINITION_DUPLICATE_ID",
  crossSectionGridDefinitionMissingId: "LINER_CROSS_SECTION_GRID_DEFINITION_MISSING_ID",
  crossSectionTemplateReferenceMissing: "LINER_CROSS_SECTION_TEMPLATE_REFERENCE_MISSING",
  crossSectionOffsetLineReferenceMissing: "LINER_CROSS_SECTION_OFFSET_LINE_REFERENCE_MISSING",
  crossSectionGridDefinitionInvalidRange: "LINER_CROSS_SECTION_GRID_DEFINITION_INVALID_RANGE",
  crossSectionGridDefinitionOverlap: "LINER_CROSS_SECTION_GRID_DEFINITION_OVERLAP",
} as const satisfies Record<string, LinerDiagnosticCode>;

export const LINER_DIAGNOSTIC_MESSAGE_KEYS = {
  LINER_GEOM_ZERO_LENGTH_SEGMENT: "liner.errors.geom_zero_length",
  LINER_GEOM_POSITION_DISCONTINUITY: "liner.errors.geom_position_gap",
  LINER_GEOM_AZIMUTH_DISCONTINUITY: "liner.errors.geom_azimuth_gap",
  LINER_GEOM_CLOTHOID_INVALID_RADIUS: "liner.errors.geom_clothoid_radius",
  LINER_GEOM_CLOTHOID_ACCURACY_EXCEEDED: "liner.errors.geom_clothoid_accuracy",
  LINER_GEOM_CLOTHOID_LONG_SPIRAL: "liner.errors.geom_clothoid_long",
  LINER_GEOM_INVERSE_PROJECTION_FAILED: "liner.errors.geom_inverse_failed",
  LINER_STATION_DUPLICATE_EQUATION: "liner.errors.station_duplicate",
  LINER_STATION_OUT_OF_RANGE: "liner.errors.station_range",
  LINER_GRID_SPACING_INVALID: "liner.errors.grid_spacing",
  LINER_FRAME_MISSING_NODE: "liner.errors.frame_missing_node",
  LINER_FRAME_MISSING_SECTION: "liner.errors.frame_missing_section",
  LINER_FRAME_ZERO_LENGTH_MEMBER: "liner.errors.frame_zero_member",
  LINER_FRAME_DISCONNECTED: "liner.errors.frame_disconnected",
  LINER_FRAME_DUPLICATE_ID: "liner.errors.frame_duplicate_id",
  LINER_FRAME_SCHEMA_INVALID: "liner.errors.frame_schema",
  LINER_PROFILE_ELEVATION_DISCONTINUITY: "liner.errors.profile_elevation_gap",
  LINER_PROFILE_GRADE_DISCONTINUITY: "liner.errors.profile_grade_gap",
  LINER_PROFILE_COVERAGE_GAP: "liner.errors.profile_coverage_gap",
  LINER_PROFILE_ADJACENCY_GAP: "liner.errors.profile_adjacency_gap",
  LINER_PROFILE_END_COVERAGE_GAP: "liner.errors.profile_end_coverage_gap",
  LINER_PROFILE_OVERLAP: "liner.errors.profile_overlap",
  LINER_PROFILE_GRADE_EXCEEDS_LIMIT: "liner.errors.profile_grade_exceeds_limit",
  LINER_SPAN_END_EXCEEDS_ALIGNMENT: "liner.errors.span_end_exceeds_alignment",
  LINER_ORIGIN_STATION_AMBIGUOUS: "liner.errors.origin_station_ambiguous",
  LINER_PROFILE_PARABOLIC_Z_MERGE_DEFERRED: "liner.errors.profile_parabolic_z_merge_deferred",
  LINER_CROSSFALL_INTERVAL_OVERLAP: "liner.errors.crossfall_interval_overlap",
  LINER_CROSSFALL_INTERVAL_INVALID_RANGE: "liner.errors.crossfall_interval_invalid_range",
  LINER_CROSSFALL_PIVOT_CHANGE_UNSUPPORTED: "liner.errors.crossfall_pivot_change_unsupported",
  LINER_CROSSFALL_MEASURED_GRID_PRECEDENCE: "liner.errors.crossfall_measured_grid_precedence",
  LINER_WIDTH_CHANGE_POINT_OVERLAP: "liner.errors.width_change_point_overlap",
  LINER_WIDTH_CHANGE_POINT_OUT_OF_RANGE: "liner.errors.width_change_point_out_of_range",
  LINER_WIDTH_CHANGE_POINT_INVALID: "liner.errors.width_change_point_invalid",
  LINER_CROSS_SECTION_TEMPLATE_DUPLICATE_ID: "liner.errors.cross_section_template_duplicate_id",
  LINER_CROSS_SECTION_TEMPLATE_MISSING_ID: "liner.errors.cross_section_template_missing_id",
  LINER_CROSS_SECTION_OFFSET_LINE_DUPLICATE_ID: "liner.errors.cross_section_offset_line_duplicate_id",
  LINER_CROSS_SECTION_OFFSET_LINE_MISSING_ID: "liner.errors.cross_section_offset_line_missing_id",
  LINER_CROSS_SECTION_OFFSET_LINE_MISSING: "liner.errors.cross_section_offset_line_missing",
  LINER_CROSS_SECTION_GRID_DEFINITION_DUPLICATE_ID: "liner.errors.cross_section_grid_definition_duplicate_id",
  LINER_CROSS_SECTION_GRID_DEFINITION_MISSING_ID: "liner.errors.cross_section_grid_definition_missing_id",
  LINER_CROSS_SECTION_TEMPLATE_REFERENCE_MISSING: "liner.errors.cross_section_template_reference_missing",
  LINER_CROSS_SECTION_OFFSET_LINE_REFERENCE_MISSING: "liner.errors.cross_section_offset_line_reference_missing",
  LINER_CROSS_SECTION_GRID_DEFINITION_INVALID_RANGE: "liner.errors.cross_section_grid_definition_invalid_range",
  LINER_CROSS_SECTION_GRID_DEFINITION_OVERLAP: "liner.errors.cross_section_grid_definition_overlap",
} as const satisfies Record<LinerDiagnosticCode, `liner.errors.${string}`>;

export function createIssue(
  level: DiagnosticLevel,
  code: LinerDiagnosticCode,
  extra: Omit<ValidationIssue, "level" | "code"> = {},
): ValidationIssue {
  return {
    level,
    code,
    messageKey: LINER_DIAGNOSTIC_MESSAGE_KEYS[code],
    ...extra,
  };
}

export function hasFatalIssues(issues: ValidationIssue[]): boolean {
  return issues.some((issue) => issue.level === "error");
}
